# -*- coding: utf-8 -*-
"""3-YAKUNIY VAZIFA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13HQ9V3_A4pBXPZ6TzRnhdfX4xexy1UhX
"""

import numpy as np

def load_data(file_name):
  cars_file=np.load(file_name)
  m=cars_file['models']
  q=cars_file['qnts']
  return m,q

m,q=load_data('GM_Cars/gm_2020.npz')
m

def total_qnts():
    m_2020,q_2020 = load_data('GM_Cars/gm_2020.npz')
    m_2021,q_2021 = load_data('GM_Cars/gm_2021.npz')
    a=sum(q_2020)
    b=sum(q_2021)
    return a,b

total_qnts()

def sel_models():
    m_2020,q_2020 = load_data('GM_Cars/gm_2020.npz')
    m_2021,q_2021 = load_data('GM_Cars/gm_2021.npz')
    special_cars_2020=(m_2020=='Damas') | (m_2020=='Nexia') | (m_2020=='Cobalt') | (m_2020=='Gentra')
    special_cars_2021=(m_2021=='Damas') | (m_2021=='Nexia') | (m_2021=='Cobalt') | (m_2021=='Gentra')
    return q_2020[special_cars_2020],q_2021[special_cars_2021]
    #Damas, Nexia, Cobalt, va Gentra

cars_2020,cars_2021=sel_models()
print('2020-yilda Damas avtomashinasi ',cars_2020[0],'ta ishlab chiqarilgan,2021-yilda esa',cars_2021[0],'ta')
print('2020-yilda Nexia avtomashinasi ',cars_2020[1],'ta ishlab chiqarilgan,2021-yilda esa',cars_2021[1],'ta')
print('2020-yilda Cobalt avtomashinasi ',cars_2020[2],'ta ishlab chiqarilgan,2021-yilda esa',cars_2021[2],'ta')
print('2020-yilda Gentra avtomashinasi ',cars_2020[3],'ta ishlab chiqarilgan,2021-yilda esa',cars_2021[3],'ta')

def ratio_sel_models():
  cars_2020,cars_2021=sel_models() # har 4ta mashina uchun 2020 va 2021da ishlab chiqarish miqdori
  damas2020=cars_2020[0]
  nexia2020=cars_2020[1]
  cobalt2020=cars_2020[2]
  gentra2020=cars_2020[3]
  damas2021=cars_2021[0]
  nexia2021=cars_2021[1]
  cobalt2021=cars_2021[2]
  gentra2021=cars_2021[3]
  quantities_2020,quantities_2021 = total_qnts() # 2020 va 2021 da jami ishlab chiqarilgan mashinalar miqdori
  damas_2020=(damas2020/quantities_2020)*100
  nexia_2020=(nexia2020/quantities_2020)*100
  cobalt_2020=(cobalt2020/quantities_2020)*100
  gentra_2020=(gentra2020/quantities_2020)*100
  damas_2021=(damas2021/quantities_2021)*100
  nexia_2021=(nexia2021/quantities_2021)*100
  cobalt_2021=(cobalt2021/quantities_2021)*100
  gentra_2021=(gentra2021/quantities_2021)*100
  jami_2020=[damas_2020,nexia_2020,cobalt_2020,gentra_2020]
  jami_2021=[damas_2021,nexia_2021,cobalt_2021,gentra_2021]

  return jami_2020,jami_2021

jami_2020,jami_2021=ratio_sel_models()
print('Damas rusumli avtomabil 2020 yilda jami ishlab chiqarishning', jami_2020[0],'% ni tashkil etadi 2021 yilda esa', jami_2021[0],'% ni tashkil etmoqda ')
print('Nexia rusumli avtomabil 2020 yilda jami ishlab chiqarishning', jami_2020[1],'% ni tashkil etadi 2021 yilda esa', jami_2021[1],'% ni tashkil etmoqda ')
print('Cobalt rusumli avtomabil 2020 yilda jami ishlab chiqarishning', jami_2020[2],'% ni tashkil etadi 2021 yilda esa', jami_2021[2],'% ni tashkil etmoqda ')
print('Gentra rusumli avtomabil 2020 yilda jami ishlab chiqarishning', jami_2020[3],'% ni tashkil etadi 2021 yilda esa', jami_2021[3],'% ni tashkil etmoqda ')