# -*- coding: utf-8 -*-
"""3-YAKUNIY VAZIFA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13HQ9V3_A4pBXPZ6TzRnhdfX4xexy1UhX
"""

import numpy as np

def load_data(file_name):
  cars_file=np.load(file_name)
  m=cars_file['models']
  q=cars_file['qnts']
  return m,q

def total_qnts():
    m_2020,q_2020 = load_data('GM_Cars/gm_2020.npz')
    m_2021,q_2021 = load_data('GM_Cars/gm_2021.npz')
    a=sum(q_2020)
    b=sum(q_2021)
    return a,b

def sel_models():
    m_2020,q_2020 = load_data('GM_Cars/gm_2020.npz')
    m_2021,q_2021 = load_data('GM_Cars/gm_2021.npz')
    special_cars_2020=(m_2020=='Damas') | (m_2020=='Nexia') | (m_2020=='Cobalt') | (m_2020=='Gentra')
    special_cars_2021=(m_2021=='Damas') | (m_2021=='Nexia') | (m_2021=='Cobalt') | (m_2021=='Gentra')
    return q_2020[special_cars_2020],q_2021[special_cars_2021]
    #Damas, Nexia, Cobalt, and Gentra

cars_2020,cars_2021=sel_models()
print('In 2020, the Damas car was produced by ',cars_2020[0],'and in 2021, ',cars_2021[0])
print('In 2020, the Nexia car was produced by ',cars_2020[1],'and in 2021, ',cars_2021[1])
print('In 2020, the Cobalt car was produced by ',cars_2020[2],'and in 2021, ',cars_2021[2])
print('In 2020, the Gentra car was produced by ',cars_2020[3],'and in 2021, ',cars_2021[3])

def ratio_sel_models():
  cars_2020,cars_2021=sel_models() # production volume in 2020 and 2021 for every 4 cars
  damas2020=cars_2020[0]
  nexia2020=cars_2020[1]
  cobalt2020=cars_2020[2]
  gentra2020=cars_2020[3]
  damas2021=cars_2021[0]
  nexia2021=cars_2021[1]
  cobalt2021=cars_2021[2]
  gentra2021=cars_2021[3]
  quantities_2020,quantities_2021 = total_qnts() # Total number of cars produced in 2020 and 2021
  damas_2020=(damas2020/quantities_2020)*100
  nexia_2020=(nexia2020/quantities_2020)*100
  cobalt_2020=(cobalt2020/quantities_2020)*100
  gentra_2020=(gentra2020/quantities_2020)*100
  damas_2021=(damas2021/quantities_2021)*100
  nexia_2021=(nexia2021/quantities_2021)*100
  cobalt_2021=(cobalt2021/quantities_2021)*100
  gentra_2021=(gentra2021/quantities_2021)*100
  total_2020=[damas_2020,nexia_2020,cobalt_2020,gentra_2020]
  total_2021=[damas_2021,nexia_2021,cobalt_2021,gentra_2021]

  return total_2020,total_2021

total_2020,total_2021=ratio_sel_models()
print('Damas automobile makes up',total_2020[0],'% of total production in 2020 and',total_2021[0],'% in 2021')
print('Nexia car will make up',total_2020[1],'% of total production in 2020 and',total_2021[1],'% in 2021')
print('Cobalt makes up',total_2020[2],'% of total production in 2020 and',total_2021[2],'% in 2021')
print('Gentra makes up',total_2020[3],'% of total production in 2020 and',total_2021[3],'% in 2021')